#:kivy 1.10.0
<Launch>
    PageLayout:
        BoxLayout:
            canvas:
                Color:
                    rgba: 216/255., 195/255., 88/255., 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            orientation: 'vertical'
            Label:
                size_hint_y: None
                height: 1.5 * self.texture_size[1]
                text: 'page 1'
            Button:
                text: 'test'
                on_press: root.say_hello()
