#:kivy 1.10.0

<Connected>:
    BoxLayout:
        orientation: 'vertical'

        Label:
            text: "You are now connected"
            font_size: 32
        Button:
            text: "Disconnect"
            font_size: 24
            on_press: root.disconnect()

<GoToTheApp>
	FloatLayout:
		canvas:
    		Color:
        		rgba: 255/255., 255/255., 255/255., 1
			Rectangle:
                pos: self.pos
                size: self.size
		AnchorLayout:
			anchor_x: 'center'
			anchor_y: 'top'
			ScrollView:
        		size_hint: (None, None)
        		size: (400, 400)
        		GridLayout:
            		id: output
            		cols: 1
            		size_hint_y: 300
            		height: self.minimum_height
					
					Label:
            			text: 'Dishcovery è il servizio più utilizzato dai ristoratori italiani per creare pratici ed efficienti menù digitali multi-lingua. L’unico capace di raccontare oltre che tradurre.\n
				ICONA da fare (te la farò avere)\n
				Traduciamo il tuo menù utilizzando solo traduttori madrelingua specializzati e applicando processi certificati ISO\n
				ICONA da fare (te la farò avere)\n
				Creiamo un menù digitale contenente tutti i tuoi menù collegati ad un codice QR accessibile da tutti gli smartphone senza scaricare nessuna app\n
				ICONA da fare (te la farò avere)\n
				 nostri menù digitali non offrono solo la traduzione. I tuoi ospiti potranno vedere anche la descrizione dei tuoi ingredienti, piatti, abbinamenti consigliati e molto altro'
            			font_size: 32

		AnchorLayout:
			anchor_x: 'center'
			anchor_y: 'bottom'
			Button:
				size: 200, 100
				size_hint: None, None
				text: 'Go to the app'
				on_press: root.next()

<Login>:
    BoxLayout:
        id: login_layout
        orientation: 'vertical'
        padding: [10,50,10,50]
        spacing: 24

        Label:
            text: 'Welcome'
            font_size: 32

        BoxLayout:
            orientation: 'vertical'

            Label:
                text: 'Login'
                font_size: 18
                halign: 'left'
                text_size: root.width-20, 20

            TextInput:
                id: login
                multiline:False
                font_size: 28

        BoxLayout:
            orientation: 'vertical'
            Label:
                text: 'Password'
                halign: 'left'
                font_size: 18
                text_size: root.width-20, 20

            TextInput:
                id: password
                multiline:False
                password:True
                font_size: 28

		BoxLayout:
			orientation: 'vertical'
            Label:
                text: 'Telefono'
                halign: 'left'
                font_size: 18
                text_size: root.width-20, 20

            TextInput:
                id: telefono
                multiline:False
                font_size: 28

		BoxLayout:
			orientation: 'vertical'
            Label:
                text: 'Città'
                halign: 'left'
                font_size: 18
                text_size: root.width-20, 20

            TextInput:
                id: citta
                multiline:False
                font_size: 28
		
		BoxLayout:
			orientation: 'vertical'
            Label:
                text: 'Via'
                halign: 'left'
                font_size: 18
                text_size: root.width-20, 20

            TextInput:
                id: via
                multiline:False
                font_size: 28
		
		BoxLayout:
			orientation: 'vertical'
            Label:
                text: 'Mail'
                halign: 'left'
                font_size: 18
                text_size: root.width-20, 20

            TextInput:
                id: mail
                multiline:False
                font_size: 28

        Button:
            text: 'Connexion'
            font_size: 24
            on_press: root.do_login(login.text, password.text, telefono.text, citta.text, via.text, mail.text)


	

<Redirect>
	FloatLayout:
		canvas:
    		Color:
        		rgba: 255/255., 255/255., 255/255., 1
			Rectangle:
                pos: self.pos
                size: self.size
		AnchorLayout:
			anchor_x: 'left'
			anchor_y: 'top'
			Image:
				size_hint: None, None
				source: 'logo.png'
		AnchorLayout:
			anchor_x: 'right'
			anchor_y: 'top'
			Image:
				size_hint: None, None
				source: 'logo.png'
		AnchorLayout:
			anchor_x: 'center'
			anchor_y: 'top'
			Label:
				color: 0, 0, 0, 1
				size_hint: None, None
				text: 'Dischovery Menu'
		AnchorLayout:
			anchor_x: 'center'
			anchor_y: 'center'
			Label:
				color: 0, 0, 0, 1
				size_hint: None, None
				text: 'Dishcovery è il servizio più utilizzato\ndai ristoratori italiani\nper creare pratici ed efficienti\nmenù digitali multi-lingua.\nL’unico capace di raccontare\noltre che tradurre.'
		AnchorLayout:
			anchor_x: 'left'
			anchor_y: 'bottom'
			Button:
				size: 200, 100
				size_hint: None, None
				text: 'Go to dischovery'
				on_press: root.redirect()
		AnchorLayout:
			anchor_x: 'right'
			anchor_y: 'bottom'
			Button:
				size: 200, 100
				size_hint: None, None
				text: 'Next'
				on_press: root.next()
		
				

